// SlurmLite gRPC API definitions.
//
// Generate Go code with:
//   protoc --go_out=. --go_opt=module=github.com/vittalayer/distr-scheduling \
//     --go-grpc_out=. --go-grpc_opt=module=github.com/vittalayer/distr-scheduling \
//     api/proto/v1/scheduler.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: api/proto/v1/scheduler.proto

package slurmlitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_scheduler_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 2
	NodeStatus_NODE_STATUS_BUSY        NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_BUSY",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_OFFLINE":     2,
		"NODE_STATUS_BUSY":        3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_scheduler_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

// Event reported by a node for an assigned job.
type JobEvent int32

const (
	JobEvent_JOB_EVENT_UNSPECIFIED JobEvent = 0
	JobEvent_JOB_EVENT_STARTED     JobEvent = 1
	JobEvent_JOB_EVENT_COMPLETED   JobEvent = 2
	JobEvent_JOB_EVENT_FAILED      JobEvent = 3
	JobEvent_JOB_EVENT_CANCELLED   JobEvent = 4
)

// Enum value maps for JobEvent.
var (
	JobEvent_name = map[int32]string{
		0: "JOB_EVENT_UNSPECIFIED",
		1: "JOB_EVENT_STARTED",
		2: "JOB_EVENT_COMPLETED",
		3: "JOB_EVENT_FAILED",
		4: "JOB_EVENT_CANCELLED",
	}
	JobEvent_value = map[string]int32{
		"JOB_EVENT_UNSPECIFIED": 0,
		"JOB_EVENT_STARTED":     1,
		"JOB_EVENT_COMPLETED":   2,
		"JOB_EVENT_FAILED":      3,
		"JOB_EVENT_CANCELLED":   4,
	}
)

func (x JobEvent) Enum() *JobEvent {
	p := new(JobEvent)
	*p = x
	return p
}

func (x JobEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_scheduler_proto_enumTypes[2].Descriptor()
}

func (JobEvent) Type() protoreflect.EnumType {
	return &file_api_proto_v1_scheduler_proto_enumTypes[2]
}

func (x JobEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobEvent.Descriptor instead.
func (JobEvent) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

// ResourceRequest is the gang-scheduling constraint for a job.
// The scheduler allocates only when nodes_required nodes each have at least
// cpus_per_node free CPUs. Partial allocation is never valid.
type ResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of nodes that must be allocated together. Must be >= 1.
	NodesRequired int32 `protobuf:"varint,1,opt,name=nodes_required,json=nodesRequired,proto3" json:"nodes_required,omitempty"`
	// CPUs reserved on each allocated node. Must be >= 1.
	CpusPerNode int32 `protobuf:"varint,2,opt,name=cpus_per_node,json=cpusPerNode,proto3" json:"cpus_per_node,omitempty"`
	// Optional wall-clock limit. Nodes kill the process if exceeded.
	MaxDuration   *durationpb.Duration `protobuf:"bytes,3,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequest) GetNodesRequired() int32 {
	if x != nil {
		return x.NodesRequired
	}
	return 0
}

func (x *ResourceRequest) GetCpusPerNode() int32 {
	if x != nil {
		return x.CpusPerNode
	}
	return 0
}

func (x *ResourceRequest) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

// JobSpec is what slctl submit sends: resources plus the program to run.
type JobSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Resources *ResourceRequest       `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	// Executable path or name (argv[0]). Must be non-empty.
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Arguments passed to the command (argv[1:]).
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// Optional user-supplied environment. The controller may add SlurmLite
	// variables (SLURMLITE_JOB_ID, SLURMLITE_NODE_RANK, SLURMLITE_NNODES)
	// when dispatching WorkAssignment.
	Env           map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *JobSpec) GetResources() *ResourceRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *JobSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Job struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=slurmlite.v1.JobStatus" json:"status,omitempty"`
	Spec   *JobSpec               `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Populated when the job is gang-scheduled.
	AssignedNodeIds []string               `protobuf:"bytes,4,rep,name=assigned_node_ids,json=assignedNodeIds,proto3" json:"assigned_node_ids,omitempty"`
	SubmittedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode        int32                  `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Job) GetAssignedNodeIds() []string {
	if x != nil {
		return x.AssignedNodeIds
	}
	return nil
}

func (x *Job) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Job) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type NodeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Controller may assign an ID if empty.
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Address the node is reachable at, if the controller ever dials it.
	Address       string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TotalCpus     int32  `protobuf:"varint,4,opt,name=total_cpus,json=totalCpus,proto3" json:"total_cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *NodeSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeSpec) GetTotalCpus() int32 {
	if x != nil {
		return x.TotalCpus
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Status        NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=slurmlite.v1.NodeStatus" json:"status,omitempty"`
	TotalCpus     int32                  `protobuf:"varint,5,opt,name=total_cpus,json=totalCpus,proto3" json:"total_cpus,omitempty"`
	AllocatedCpus int32                  `protobuf:"varint,6,opt,name=allocated_cpus,json=allocatedCpus,proto3" json:"allocated_cpus,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Empty when the node is not running a job.
	CurrentJobId  string `protobuf:"bytes,8,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Node) GetTotalCpus() int32 {
	if x != nil {
		return x.TotalCpus
	}
	return 0
}

func (x *Node) GetAllocatedCpus() int32 {
	if x != nil {
		return x.AllocatedCpus
	}
	return 0
}

func (x *Node) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *Node) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

// WorkAssignment is pushed to each allocated node when a job is gang-scheduled.
type WorkAssignment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobId       string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command     string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args        []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env         map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxDuration *durationpb.Duration   `protobuf:"bytes,5,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	// Rank of this node in the allocation (0 .. nnodes-1).
	NodeRank int32 `protobuf:"varint,6,opt,name=node_rank,json=nodeRank,proto3" json:"node_rank,omitempty"`
	// Total nodes in the allocation (same as resources.nodes_required).
	Nnodes        int32 `protobuf:"varint,7,opt,name=nnodes,proto3" json:"nnodes,omitempty"`
	CpusPerNode   int32 `protobuf:"varint,8,opt,name=cpus_per_node,json=cpusPerNode,proto3" json:"cpus_per_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkAssignment) Reset() {
	*x = WorkAssignment{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAssignment) ProtoMessage() {}

func (x *WorkAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAssignment.ProtoReflect.Descriptor instead.
func (*WorkAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *WorkAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WorkAssignment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *WorkAssignment) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WorkAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *WorkAssignment) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

func (x *WorkAssignment) GetNodeRank() int32 {
	if x != nil {
		return x.NodeRank
	}
	return 0
}

func (x *WorkAssignment) GetNnodes() int32 {
	if x != nil {
		return x.Nnodes
	}
	return 0
}

func (x *WorkAssignment) GetCpusPerNode() int32 {
	if x != nil {
		return x.CpusPerNode
	}
	return 0
}

type CancelWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWork) Reset() {
	*x = CancelWork{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWork) ProtoMessage() {}

func (x *CancelWork) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWork.ProtoReflect.Descriptor instead.
func (*CancelWork) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CancelWork) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *JobSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitJobRequest) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means all statuses.
	Statuses      []JobStatus `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=slurmlite.v1.JobStatus" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *ListJobsRequest) GetStatuses() []JobStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *CancelJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{13}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *NodeSpec              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterNodeRequest) GetSpec() *NodeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AllocatedCpus int32                  `protobuf:"varint,2,opt,name=allocated_cpus,json=allocatedCpus,proto3" json:"allocated_cpus,omitempty"`
	CurrentJobId  string                 `protobuf:"bytes,3,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAllocatedCpus() int32 {
	if x != nil {
		return x.AllocatedCpus
	}
	return 0
}

func (x *HeartbeatRequest) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// If set, the node should stop this job even if WatchWork is down.
	CancelJobId   string `protobuf:"bytes,2,opt,name=cancel_job_id,json=cancelJobId,proto3" json:"cancel_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCancelJobId() string {
	if x != nil {
		return x.CancelJobId
	}
	return ""
}

type ReportJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Event         JobEvent               `protobuf:"varint,3,opt,name=event,proto3,enum=slurmlite.v1.JobEvent" json:"event,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusRequest) Reset() {
	*x = ReportJobStatusRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusRequest) ProtoMessage() {}

func (x *ReportJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *ReportJobStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportJobStatusRequest) GetEvent() JobEvent {
	if x != nil {
		return x.Event
	}
	return JobEvent_JOB_EVENT_UNSPECIFIED
}

func (x *ReportJobStatusRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportJobStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusResponse) Reset() {
	*x = ReportJobStatusResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusResponse) ProtoMessage() {}

func (x *ReportJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *ReportJobStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type WatchWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchWorkRequest) Reset() {
	*x = WatchWorkRequest{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkRequest) ProtoMessage() {}

func (x *WatchWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *WatchWorkRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type WatchWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WatchWorkResponse_Assignment
	//	*WatchWorkResponse_Cancel
	Payload       isWatchWorkResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchWorkResponse) Reset() {
	*x = WatchWorkResponse{}
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkResponse) ProtoMessage() {}

func (x *WatchWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkResponse.ProtoReflect.Descriptor instead.
func (*WatchWorkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *WatchWorkResponse) GetPayload() isWatchWorkResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WatchWorkResponse) GetAssignment() *WorkAssignment {
	if x != nil {
		if x, ok := x.Payload.(*WatchWorkResponse_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *WatchWorkResponse) GetCancel() *CancelWork {
	if x != nil {
		if x, ok := x.Payload.(*WatchWorkResponse_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isWatchWorkResponse_Payload interface {
	isWatchWorkResponse_Payload()
}

type WatchWorkResponse_Assignment struct {
	Assignment *WorkAssignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

type WatchWorkResponse_Cancel struct {
	Cancel *CancelWork `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*WatchWorkResponse_Assignment) isWatchWorkResponse_Payload() {}

func (*WatchWorkResponse_Cancel) isWatchWorkResponse_Payload() {}

var File_api_proto_v1_scheduler_proto protoreflect.FileDescriptor

const file_api_proto_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/scheduler.proto\x12\fslurmlite.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\x0fResourceRequest\x12%\n" +
	"\x0enodes_required\x18\x01 \x01(\x05R\rnodesRequired\x12\"\n" +
	"\rcpus_per_node\x18\x02 \x01(\x05R\vcpusPerNode\x12<\n" +
	"\fmax_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\"\xde\x01\n" +
	"\aJobSpec\x12;\n" +
	"\tresources\x18\x01 \x01(\v2\x1d.slurmlite.v1.ResourceRequestR\tresources\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.slurmlite.v1.JobSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.slurmlite.v1.JobStatusR\x06status\x12)\n" +
	"\x04spec\x18\x03 \x01(\v2\x15.slurmlite.v1.JobSpecR\x04spec\x12*\n" +
	"\x11assigned_node_ids\x18\x04 \x03(\tR\x0fassignedNodeIds\x12=\n" +
	"\fsubmitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"o\n" +
	"\bNodeSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"total_cpus\x18\x04 \x01(\x05R\ttotalCpus\"\xad\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.slurmlite.v1.NodeStatusR\x06status\x12\x1d\n" +
	"\n" +
	"total_cpus\x18\x05 \x01(\x05R\ttotalCpus\x12%\n" +
	"\x0eallocated_cpus\x18\x06 \x01(\x05R\rallocatedCpus\x12A\n" +
	"\x0elast_heartbeat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12$\n" +
	"\x0ecurrent_job_id\x18\b \x01(\tR\fcurrentJobId\"\xdd\x02\n" +
	"\x0eWorkAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x127\n" +
	"\x03env\x18\x04 \x03(\v2%.slurmlite.v1.WorkAssignment.EnvEntryR\x03env\x12<\n" +
	"\fmax_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\x12\x1b\n" +
	"\tnode_rank\x18\x06 \x01(\x05R\bnodeRank\x12\x16\n" +
	"\x06nnodes\x18\a \x01(\x05R\x06nnodes\x12\"\n" +
	"\rcpus_per_node\x18\b \x01(\x05R\vcpusPerNode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\n" +
	"CancelWork\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"=\n" +
	"\x10SubmitJobRequest\x12)\n" +
	"\x04spec\x18\x01 \x01(\v2\x15.slurmlite.v1.JobSpecR\x04spec\"8\n" +
	"\x11SubmitJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.slurmlite.v1.JobR\x03job\"F\n" +
	"\x0fListJobsRequest\x123\n" +
	"\bstatuses\x18\x01 \x03(\x0e2\x17.slurmlite.v1.JobStatusR\bstatuses\"9\n" +
	"\x10ListJobsResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.slurmlite.v1.JobR\x04jobs\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"8\n" +
	"\x11CancelJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.slurmlite.v1.JobR\x03job\"\x12\n" +
	"\x10ListNodesRequest\"=\n" +
	"\x11ListNodesResponse\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.slurmlite.v1.NodeR\x05nodes\"A\n" +
	"\x13RegisterNodeRequest\x12*\n" +
	"\x04spec\x18\x01 \x01(\v2\x16.slurmlite.v1.NodeSpecR\x04spec\"/\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"x\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eallocated_cpus\x18\x02 \x01(\x05R\rallocatedCpus\x12$\n" +
	"\x0ecurrent_job_id\x18\x03 \x01(\tR\fcurrentJobId\"[\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\"\n" +
	"\rcancel_job_id\x18\x02 \x01(\tR\vcancelJobId\"\xb8\x01\n" +
	"\x16ReportJobStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12,\n" +
	"\x05event\x18\x03 \x01(\x0e2\x16.slurmlite.v1.JobEventR\x05event\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"=\n" +
	"\x17ReportJobStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"+\n" +
	"\x10WatchWorkRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x92\x01\n" +
	"\x11WatchWorkResponse\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1c.slurmlite.v1.WorkAssignmentH\x00R\n" +
	"assignment\x122\n" +
	"\x06cancel\x18\x02 \x01(\v2\x18.slurmlite.v1.CancelWorkH\x00R\x06cancelB\t\n" +
	"\apayload*\xa2\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x05*p\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x03*\x84\x01\n" +
	"\bJobEvent\x12\x19\n" +
	"\x15JOB_EVENT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_EVENT_STARTED\x10\x01\x12\x17\n" +
	"\x13JOB_EVENT_COMPLETED\x10\x02\x12\x14\n" +
	"\x10JOB_EVENT_FAILED\x10\x03\x12\x17\n" +
	"\x13JOB_EVENT_CANCELLED\x10\x042\x9d\x05\n" +
	"\x11ControllerService\x12L\n" +
	"\tSubmitJob\x12\x1e.slurmlite.v1.SubmitJobRequest\x1a\x1f.slurmlite.v1.SubmitJobResponse\x12I\n" +
	"\bListJobs\x12\x1d.slurmlite.v1.ListJobsRequest\x1a\x1e.slurmlite.v1.ListJobsResponse\x12L\n" +
	"\tCancelJob\x12\x1e.slurmlite.v1.CancelJobRequest\x1a\x1f.slurmlite.v1.CancelJobResponse\x12L\n" +
	"\tListNodes\x12\x1e.slurmlite.v1.ListNodesRequest\x1a\x1f.slurmlite.v1.ListNodesResponse\x12U\n" +
	"\fRegisterNode\x12!.slurmlite.v1.RegisterNodeRequest\x1a\".slurmlite.v1.RegisterNodeResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.slurmlite.v1.HeartbeatRequest\x1a\x1f.slurmlite.v1.HeartbeatResponse\x12^\n" +
	"\x0fReportJobStatus\x12$.slurmlite.v1.ReportJobStatusRequest\x1a%.slurmlite.v1.ReportJobStatusResponse\x12N\n" +
	"\tWatchWork\x12\x1e.slurmlite.v1.WatchWorkRequest\x1a\x1f.slurmlite.v1.WatchWorkResponse0\x01BAZ?github.com/vittalayer/distr-scheduling/api/proto/v1;slurmlitev1b\x06proto3"

var (
	file_api_proto_v1_scheduler_proto_rawDescOnce sync.Once
	file_api_proto_v1_scheduler_proto_rawDescData []byte
)

func file_api_proto_v1_scheduler_proto_rawDescGZIP() []byte {
	file_api_proto_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_scheduler_proto_rawDesc), len(file_api_proto_v1_scheduler_proto_rawDesc)))
	})
	return file_api_proto_v1_scheduler_proto_rawDescData
}

var file_api_proto_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_v1_scheduler_proto_goTypes = []any{
	(JobStatus)(0),                  // 0: slurmlite.v1.JobStatus
	(NodeStatus)(0),                 // 1: slurmlite.v1.NodeStatus
	(JobEvent)(0),                   // 2: slurmlite.v1.JobEvent
	(*ResourceRequest)(nil),         // 3: slurmlite.v1.ResourceRequest
	(*JobSpec)(nil),                 // 4: slurmlite.v1.JobSpec
	(*Job)(nil),                     // 5: slurmlite.v1.Job
	(*NodeSpec)(nil),                // 6: slurmlite.v1.NodeSpec
	(*Node)(nil),                    // 7: slurmlite.v1.Node
	(*WorkAssignment)(nil),          // 8: slurmlite.v1.WorkAssignment
	(*CancelWork)(nil),              // 9: slurmlite.v1.CancelWork
	(*SubmitJobRequest)(nil),        // 10: slurmlite.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),       // 11: slurmlite.v1.SubmitJobResponse
	(*ListJobsRequest)(nil),         // 12: slurmlite.v1.ListJobsRequest
	(*ListJobsResponse)(nil),        // 13: slurmlite.v1.ListJobsResponse
	(*CancelJobRequest)(nil),        // 14: slurmlite.v1.CancelJobRequest
	(*CancelJobResponse)(nil),       // 15: slurmlite.v1.CancelJobResponse
	(*ListNodesRequest)(nil),        // 16: slurmlite.v1.ListNodesRequest
	(*ListNodesResponse)(nil),       // 17: slurmlite.v1.ListNodesResponse
	(*RegisterNodeRequest)(nil),     // 18: slurmlite.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 19: slurmlite.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),        // 20: slurmlite.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 21: slurmlite.v1.HeartbeatResponse
	(*ReportJobStatusRequest)(nil),  // 22: slurmlite.v1.ReportJobStatusRequest
	(*ReportJobStatusResponse)(nil), // 23: slurmlite.v1.ReportJobStatusResponse
	(*WatchWorkRequest)(nil),        // 24: slurmlite.v1.WatchWorkRequest
	(*WatchWorkResponse)(nil),       // 25: slurmlite.v1.WatchWorkResponse
	nil,                             // 26: slurmlite.v1.JobSpec.EnvEntry
	nil,                             // 27: slurmlite.v1.WorkAssignment.EnvEntry
	(*durationpb.Duration)(nil),     // 28: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),   // 29: google.protobuf.Timestamp
}
var file_api_proto_v1_scheduler_proto_depIdxs = []int32{
	28, // 0: slurmlite.v1.ResourceRequest.max_duration:type_name -> google.protobuf.Duration
	3,  // 1: slurmlite.v1.JobSpec.resources:type_name -> slurmlite.v1.ResourceRequest
	26, // 2: slurmlite.v1.JobSpec.env:type_name -> slurmlite.v1.JobSpec.EnvEntry
	0,  // 3: slurmlite.v1.Job.status:type_name -> slurmlite.v1.JobStatus
	4,  // 4: slurmlite.v1.Job.spec:type_name -> slurmlite.v1.JobSpec
	29, // 5: slurmlite.v1.Job.submitted_at:type_name -> google.protobuf.Timestamp
	29, // 6: slurmlite.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	29, // 7: slurmlite.v1.Job.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 8: slurmlite.v1.Node.status:type_name -> slurmlite.v1.NodeStatus
	29, // 9: slurmlite.v1.Node.last_heartbeat:type_name -> google.protobuf.Timestamp
	27, // 10: slurmlite.v1.WorkAssignment.env:type_name -> slurmlite.v1.WorkAssignment.EnvEntry
	28, // 11: slurmlite.v1.WorkAssignment.max_duration:type_name -> google.protobuf.Duration
	4,  // 12: slurmlite.v1.SubmitJobRequest.spec:type_name -> slurmlite.v1.JobSpec
	5,  // 13: slurmlite.v1.SubmitJobResponse.job:type_name -> slurmlite.v1.Job
	0,  // 14: slurmlite.v1.ListJobsRequest.statuses:type_name -> slurmlite.v1.JobStatus
	5,  // 15: slurmlite.v1.ListJobsResponse.jobs:type_name -> slurmlite.v1.Job
	5,  // 16: slurmlite.v1.CancelJobResponse.job:type_name -> slurmlite.v1.Job
	7,  // 17: slurmlite.v1.ListNodesResponse.nodes:type_name -> slurmlite.v1.Node
	6,  // 18: slurmlite.v1.RegisterNodeRequest.spec:type_name -> slurmlite.v1.NodeSpec
	2,  // 19: slurmlite.v1.ReportJobStatusRequest.event:type_name -> slurmlite.v1.JobEvent
	8,  // 20: slurmlite.v1.WatchWorkResponse.assignment:type_name -> slurmlite.v1.WorkAssignment
	9,  // 21: slurmlite.v1.WatchWorkResponse.cancel:type_name -> slurmlite.v1.CancelWork
	10, // 22: slurmlite.v1.ControllerService.SubmitJob:input_type -> slurmlite.v1.SubmitJobRequest
	12, // 23: slurmlite.v1.ControllerService.ListJobs:input_type -> slurmlite.v1.ListJobsRequest
	14, // 24: slurmlite.v1.ControllerService.CancelJob:input_type -> slurmlite.v1.CancelJobRequest
	16, // 25: slurmlite.v1.ControllerService.ListNodes:input_type -> slurmlite.v1.ListNodesRequest
	18, // 26: slurmlite.v1.ControllerService.RegisterNode:input_type -> slurmlite.v1.RegisterNodeRequest
	20, // 27: slurmlite.v1.ControllerService.Heartbeat:input_type -> slurmlite.v1.HeartbeatRequest
	22, // 28: slurmlite.v1.ControllerService.ReportJobStatus:input_type -> slurmlite.v1.ReportJobStatusRequest
	24, // 29: slurmlite.v1.ControllerService.WatchWork:input_type -> slurmlite.v1.WatchWorkRequest
	11, // 30: slurmlite.v1.ControllerService.SubmitJob:output_type -> slurmlite.v1.SubmitJobResponse
	13, // 31: slurmlite.v1.ControllerService.ListJobs:output_type -> slurmlite.v1.ListJobsResponse
	15, // 32: slurmlite.v1.ControllerService.CancelJob:output_type -> slurmlite.v1.CancelJobResponse
	17, // 33: slurmlite.v1.ControllerService.ListNodes:output_type -> slurmlite.v1.ListNodesResponse
	19, // 34: slurmlite.v1.ControllerService.RegisterNode:output_type -> slurmlite.v1.RegisterNodeResponse
	21, // 35: slurmlite.v1.ControllerService.Heartbeat:output_type -> slurmlite.v1.HeartbeatResponse
	23, // 36: slurmlite.v1.ControllerService.ReportJobStatus:output_type -> slurmlite.v1.ReportJobStatusResponse
	25, // 37: slurmlite.v1.ControllerService.WatchWork:output_type -> slurmlite.v1.WatchWorkResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_v1_scheduler_proto_init() }
func file_api_proto_v1_scheduler_proto_init() {
	if File_api_proto_v1_scheduler_proto != nil {
		return
	}
	file_api_proto_v1_scheduler_proto_msgTypes[22].OneofWrappers = []any{
		(*WatchWorkResponse_Assignment)(nil),
		(*WatchWorkResponse_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_scheduler_proto_rawDesc), len(file_api_proto_v1_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_scheduler_proto_msgTypes,
	}.Build()
	File_api_proto_v1_scheduler_proto = out.File
	file_api_proto_v1_scheduler_proto_goTypes = nil
	file_api_proto_v1_scheduler_proto_depIdxs = nil
}
